/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Moja Global Community",
  "tagline": "Learn about moja global's projects and join our ever-growing community",
  "url": "https://community.moja.global",
  "baseUrl": "/es/",
  "onBrokenLinks": "ignore",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "moja global",
  "projectName": "Community Website",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "es"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "themeConfig": {
    "algolia": {
      "appId": "",
      "apiKey": "",
      "indexName": ""
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "code_themes": {
        "light": {
          "plain": {
            "color": "#393A34",
            "backgroundColor": "#f6f8fa"
          },
          "styles": [
            {
              "types": [
                "comment",
                "prolog",
                "doctype",
                "cdata"
              ],
              "style": {
                "color": "#999988",
                "fontStyle": "italic"
              }
            },
            {
              "types": [
                "namespace"
              ],
              "style": {
                "opacity": 0.7
              }
            },
            {
              "types": [
                "string",
                "attr-value"
              ],
              "style": {
                "color": "#e3116c"
              }
            },
            {
              "types": [
                "punctuation",
                "operator"
              ],
              "style": {
                "color": "#393A34"
              }
            },
            {
              "types": [
                "entity",
                "url",
                "symbol",
                "number",
                "boolean",
                "variable",
                "constant",
                "property",
                "regex",
                "inserted"
              ],
              "style": {
                "color": "#36acaa"
              }
            },
            {
              "types": [
                "atrule",
                "keyword",
                "attr-name",
                "selector"
              ],
              "style": {
                "color": "#00a4db"
              }
            },
            {
              "types": [
                "function",
                "deleted",
                "tag"
              ],
              "style": {
                "color": "#d73a49"
              }
            },
            {
              "types": [
                "function-variable"
              ],
              "style": {
                "color": "#6f42c1"
              }
            },
            {
              "types": [
                "tag",
                "selector",
                "keyword"
              ],
              "style": {
                "color": "#00009f"
              }
            }
          ]
        },
        "dark": {
          "plain": {
            "color": "#F8F8F2",
            "backgroundColor": "#282A36"
          },
          "styles": [
            {
              "types": [
                "prolog",
                "constant",
                "builtin"
              ],
              "style": {
                "color": "rgb(189, 147, 249)"
              }
            },
            {
              "types": [
                "inserted",
                "function"
              ],
              "style": {
                "color": "rgb(80, 250, 123)"
              }
            },
            {
              "types": [
                "deleted"
              ],
              "style": {
                "color": "rgb(255, 85, 85)"
              }
            },
            {
              "types": [
                "changed"
              ],
              "style": {
                "color": "rgb(255, 184, 108)"
              }
            },
            {
              "types": [
                "punctuation",
                "symbol"
              ],
              "style": {
                "color": "rgb(248, 248, 242)"
              }
            },
            {
              "types": [
                "string",
                "char",
                "tag",
                "selector"
              ],
              "style": {
                "color": "rgb(255, 121, 198)"
              }
            },
            {
              "types": [
                "keyword",
                "variable"
              ],
              "style": {
                "color": "rgb(189, 147, 249)",
                "fontStyle": "italic"
              }
            },
            {
              "types": [
                "comment"
              ],
              "style": {
                "color": "rgb(98, 114, 164)"
              }
            },
            {
              "types": [
                "attr-name"
              ],
              "style": {
                "color": "rgb(241, 250, 140)"
              }
            }
          ]
        }
      },
      "announcementBar": {
        "id": "announcementBar",
        "backgroundColor": "#74e8a3",
        "isCloseable": true,
        "content": "If you would like to contribute, give it a star on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/kuaic\">GitHub</a> ⭐ and take a look at the open issues!"
      },
      "colorMode": {
        "defaultMode": "dark",
        "switchConfig": {
          "darkIcon": "🌙",
          "darkIconStyle": {
            "marginLeft": "2px"
          },
          "lightIcon": "💡",
          "lightIconStyle": {
            "marginLeft": "1px"
          }
        }
      },
      "navbar": {
        "title": "Community",
        "hideOnScroll": true,
        "logo": {
          "alt": "moja global Logo",
          "src": "img/logo.png",
          "srcDark": "img/logo-light.png"
        },
        "items": [
          {
            "type": "localeDropdown",
            "position": "right"
          },
          {
            "href": "https://github.com/moja-global",
            "label": "GitHub",
            "position": "right"
          },
          {
            "to": "/roadmap",
            "label": "Roadmap",
            "position": "right"
          },
          {
            "type": "doc",
            "docId": "intro",
            "position": "left",
            "label": "Projects"
          },
          {
            "to": "/blog",
            "label": "Blogs",
            "position": "left"
          },
          {
            "to": "/community/support",
            "label": "Community",
            "position": "left",
            "activeBaseRegex": "/community/"
          },
          {
            "type": "dropdown",
            "label": "Know More",
            "position": "left",
            "items": [
              {
                "label": "Initiatives",
                "href": "/initiatives"
              },
              {
                "label": "Case Studies",
                "href": "/case-studies/introduction"
              },
              {
                "label": "Tutorial",
                "href": "/tutorial/tutorial-introduction"
              }
            ]
          }
        ]
      },
      "footer": {
        "logo": {
          "alt": "moja global light logo",
          "src": "/img/logo-light.png",
          "href": "https://moja.global"
        },
        "style": "light",
        "links": [
          {
            "title": "Docs",
            "items": [
              {
                "label": "FLINT",
                "href": "https://moja.global/flint/"
              },
              {
                "label": "FLINT UI",
                "href": "https://docs.moja.global/projects/flint-ui/en/latest/"
              },
              {
                "label": "FLINT Reporting Tool",
                "href": "https://docs.moja.global/projects/flint-reporting/en/latest/"
              },
              {
                "label": "Taswira",
                "href": "https://github.com/moja-global/GCBM.Visualisation_Tool"
              },
              {
                "label": "FLINT JSON Editor",
                "href": "https://github.com/moja-global/FLINT.JSON_Interface"
              },
              {
                "label": "FLINT Cloud",
                "href": "https://docs.moja.global/projects/flintcloud/en/latest"
              }
            ]
          },
          {
            "title": "Community",
            "items": [
              {
                "label": "Projects",
                "href": "/docs"
              },
              {
                "label": "Blogs",
                "href": "/blog"
              },
              {
                "label": "Mentorship",
                "href": "/community/mentorship"
              },
              {
                "label": "Initiatives",
                "href": "/initiatives"
              },
              {
                "label": "Roadmap",
                "href": "/roadmap"
              },
              {
                "label": "Case Studies",
                "href": "/case-studies/introduction"
              },
              {
                "label": "FAQs",
                "href": "https://docs.moja.global/en/add_instructions_gdal/faq.html"
              }
            ]
          },
          {
            "title": "Getting Started",
            "items": [
              {
                "label": "About moja global",
                "href": "/docs/about-moja-global"
              },
              {
                "label": "Governance model",
                "href": "/community/governance"
              },
              {
                "label": "Contributing guidelines",
                "href": "/community/contributing"
              },
              {
                "label": "Working Groups",
                "href": "/community/working-groups/doc-wg"
              }
            ]
          },
          {
            "title": "Follow Us",
            "items": [
              {
                "html": "\n              <a href= 'https://twitter.com/mojaglobal' target=\"_blank\">\n              <img class=\"socials\" src=\"/img/twitter.png\" alt=\"twitter icon\" />\n              </a>\n              "
              },
              {
                "html": "\n              <a href= 'https://www.youtube.com/channel/UCfQUrrNP1Xf-Fv4c8uHYXhQ' target=\"_blank\">\n              <img class=\"socials\" src=\"/img/youtube.png\" alt=\"youtube icon\" />\n              </a>\n              "
              },
              {
                "html": "\n              <a href= 'https://github.com/moja-global' target=\"_blank\">\n              <img class=\"socials\" src=\"/img/github.png\" alt=\"github icon\" />\n              </a>\n              "
              },
              {
                "html": "\n              <a href= 'https://www.linkedin.com/company/moja-global/' target=\"_blank\">\n              <img class=\"socials\" src=\"/img/linkedin.png\" alt=\"linkedin icon\" />\n              </a>\n              "
              },
              {
                "html": "\n              <a href= 'https://mojaglobal.slack.com/' target=\"_blank\">\n              <img class=\"socials\" src=\"/img/slack.png\" alt=\"slack icon\" />\n              </a>\n              "
              }
            ]
          }
        ],
        "copyright": "Copyright © 2024 moja global."
      },
      "image": "https://community.moja.global/img/logo.png",
      "metadatas": [
        {
          "name": "twitter:card",
          "content": "summary_large_image"
        },
        {
          "name": "twitter:image",
          "content": "https://community.moja.global/img/logo.png"
        },
        {
          "name": "twitter:title",
          "content": "Moja Global Community"
        },
        {
          "name": "twitter:description",
          "content": "moja global is a not for profit, collaborative project that brings together a community of experts to develop open-source software that allows users to accurately and affordably estimate greenhouse gas emissions and removals from the AFOLU sector. The project’s members aim to support the widest possible use of credible emissions estimation software."
        }
      ]
    },
    "presets": [
      [
        "@docusaurus/preset-classic",
        {
          "googleAnalytics": {
            "trackingID": "",
            "anonymizeIP": true
          },
          "docs": {
            "sidebarPath": "/Users/shivramsaud/Desktop/demoRnD/sidebars.js",
            "editUrl": "https://github.com/moja-global/community-website/edit/main/website/"
          },
          "blog": {
            "showReadingTime": true,
            "editUrl": "https://github.com/moja-global/community-website/edit/main/website/blog/"
          },
          "theme": {
            "customCss": "/Users/shivramsaud/Desktop/demoRnD/src/css/custom.css"
          },
          "sitemap": {
            "changefreq": "weekly",
            "priority": 0.5,
            "trailingSlash": false
          }
        }
      ]
    ],
    "plugins": [
      [
        "@docusaurus/plugin-content-docs",
        {
          "id": "community",
          "path": "community",
          "routeBasePath": "community",
          "sidebarPath": "/Users/shivramsaud/Desktop/demoRnD/sidebarsCommunity.js"
        }
      ],
      [
        "@docusaurus/plugin-content-docs",
        {
          "id": "case-studies",
          "path": "case-studies",
          "routeBasePath": "case-studies",
          "sidebarPath": "/Users/shivramsaud/Desktop/demoRnD/sidebarsCaseStudies.js"
        }
      ],
      [
        "@docusaurus/plugin-content-docs",
        {
          "id": "tutorial-introduction",
          "path": "tutorial",
          "routeBasePath": "tutorial",
          "sidebarPath": "/Users/shivramsaud/Desktop/demoRnD/sidebarsTutorial.js"
        }
      ]
    ]
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "presets": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
