/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "KUAIC Learn",
  "tagline": "Resources for AI in Python",
  "url": "https://aiclub.ku.edu.np",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "favicon": "icon/favicon.ico",
  "organizationName": "KUAIC",
  "projectName": "rnd",
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "KUAIC Learn",
      "logo": {
        "alt": "KUAIC Logo",
        "src": "img/kuaiclogo.png"
      },
      "hideOnScroll": true,
      "items": [
        {
          "type": "docsVersion",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "type": "doc",
          "docId": "training/awe-101",
          "position": "left",
          "label": "Training",
          "activeSidebarClassName": "navbar__link--active"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "alt": "Github repository",
          "href": "https://github.com/KUAICLUB",
          "className": "header-gitlab-link",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "docs/"
            },
            {
              "label": "Migration from v3 to v4",
              "to": "docs/guides/v4-migration"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/UNnXrsKM"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Github repository",
              "href": "https://github.com/kuaiclub"
            },
            {
              "label": "Forked repository",
              "href": "https://gitlab.com/aweframework/"
            },
            {
              "html": "\n\t\t\t\t\t\t\t\t<a href=\"https://gitlab.com/aweframework/\" target=\"_blank\" rel=\"noreferrer noopener\" aria-label=\"Deploys by Netlify\">\n\t\t\t\t\t\t\t\t  <img src=\"/img/logo.svg\" alt=\"Forked From AWE\" width=\"114\" height=\"51\" />\n\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t  "
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Kathmandu University Artificial Intelligence Club, DoCSE, Kathmandu University"
    },
    "algolia": {
      "appId": "96SFT7IGN3",
      "apiKey": "87dfe5f6a5c7cf165a000b9b90539407",
      "indexName": "your_index_name",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "prism": {
      "additionalLanguages": [
        "python"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "np"
    ],
    "localeConfigs": {
      "en": {
        "label": "English",
        "direction": "ltr"
      },
      "np": {
        "label": "Nepali",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/shivramsaud/Desktop/demoRnD/sidebars.js",
          "editUrl": "https://gitlab.com/aweframework/awe/edit/master/website/",
          "includeCurrentVersion": true,
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://gitlab.com/aweframework/awe/edit/master/website/",
          "postsPerPage": 3,
          "feedOptions": {
            "type": "all",
            "language": "es",
            "copyright": "Copyright © 2024 Almis, Inc."
          }
        },
        "theme": {
          "customCss": "/Users/shivramsaud/Desktop/demoRnD/src/css/custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
